dist: trusty
sudo: false
language: python
python:
  - "3.6"
addons:
-  apt:
-    packages:
      - ffmpeg
      - build-dep
      - graphviz
      - libgfortran3
      - python-scipy
      # computation
      - libblas-dev
      - liblapack-dev
      - gfortran      
      # opencl
      - ocl-icd-opencl-dev
      - libopencl
      # cuda
      - cuda-gdb-src
      - cuda 
      - libgeos-dev
      # - python-pygame
      # - mercurial
      # - libsdl2-dev
      # - libsdl-image1.2-dev
      # - libsdl-ttf2.0-dev
      # - libsdl-mixer1.2-dev
      # - python-dev
      # for CUDA see, https://github.com/BVLC/caffe/blob/master/scripts/travis/install-deps.sh
env:
  - SDL_VIDEODRIVER=dummy SDL_AUDIODRIVER=disk KERAS_BACKEND=theano
install:
  # We do this conditionally because it saves us some downloading if the
  # version is the same.
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda install conda-build
  # Useful for debugging any issues with conda
  - conda info -a
  - conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION numpy mkl scipy nose cython scikit-learn
  - source activate test-environment
  # - make all
  #- conda build build_tools/conda-recipe --quiet
  - conda install -q --file=requirements_conda.txt
  - conda install -c conda-forge xgboost
  - pip install git+https://github.com/matplotlib/basemap.git
  - pip install -r requirements.txt
  - pip install -U git+https://github.com/sdpython/pyPdf --no-deps
  - pip install -U git+https://github.com/matplotlib/natgrid --no-deps
  # - pip install hg+http://bitbucket.org/pygame/pygame
  # we change that, cvxopt does not seem to work anymore without mkl
  # we add it at the end since it seems to modify existing packages
  - pip install https://github.com/sdpython/fairtest/releases/download/0.1/fairtest-0.1-py3-none-any.whl
  - conda install pytorch torchvision -c soumith
  - pip install torchvision
script:
  - python setup.py unittests
