environment:

  global:
    WITH_COMPILER: "cmd /E:ON /V:ON /C .\\appveyor\\run_with_compiler.cmd"

  matrix:

    - PYTHON: "C:\\Python37-x64"
      PYTHON_VERSION: "3.7.x"
      PYTHON_ARCH: "64"

init:
  - "ECHO %PYTHON% %PYTHON_VERSION% %PYTHON_ARCH%"

install:
  - "%PYTHON%\\python -m pip install --upgrade pip"
  - "%PYTHON%\\Scripts\\pip install pymyinstall"
  - "%PYTHON%\\Scripts\\pymy_install3 --set=pyensae"
  - "%PYTHON%\\Scripts\\pymy_install3 cytoolz xarray dask pylzma shapely llvmlite numexpr"
  - "%PYTHON%\\Scripts\\pymy_install3 numba scikit-image scikit-learn statsmodels pillow pyproj"
  - "%PYTHON%\\Scripts\\pymy_install3 cvxopt xgboost cartopy"
  - "%PYTHON%\\Scripts\\pymy_install3 gensim partd pygame tables"
  - "%PYTHON%\\Scripts\\pip install -r requirements_conda.txt"
  - "%PYTHON%\\Scripts\\pip install -r requirements.txt"
  - "%PYTHON%\\Scripts\\pip install -U git+https://github.com/sdpython/pyPdf --no-deps"
  - "%PYTHON%\\Scripts\\pip install tools"
  - "%PYTHON%\\Scripts\\pymy_install3 --task=tool --source=zip graphviz"
  # - "%PYTHON%\\Scripts\\pip install csharpy pythonnet"
  - "dir C:\\projects\\ensae-teaching-cs\\build\\update_modules\\Graphviz\\bin"
  - "set PATH=%PATH%;C:\\projects\\ensae-teaching-cs\\build\\update_modules\\Graphviz\\bin"

build: off

test_script:
  - "%PYTHON%\\python -u setup.py unittests"

after_test:
  - "%PYTHON%\\python -u setup.py bdist_wheel"

artifacts:
  - path: dist
    name: ensae_teaching_cs
